import json
import os
from pathlib import Path
import plistlib
import shutil
import sys

from . import config as config_module

SERVICE_NAME = "Remote Image Paste"
GHOSTTY_BUNDLE = "/Applications/Ghostty.app"
GHOSTTY_IDENTIFIER = "com.mitchellh.ghostty"


def locations(home):
    home = Path(home)
    return (
        home / "Library/Application Support/remote-image-paste",
        home / "Library/Services" / (SERVICE_NAME + ".workflow"),
        home / ".config/remote-image-paste/config.json",
    )


def _info_plist():
    return {"NSServices": [{
        "NSMenuItem": {"default": SERVICE_NAME},
        "NSMessage": "runWorkflowAsService",
        "NSRequiredContext": {"NSApplicationIdentifier": GHOSTTY_IDENTIFIER},
    }]}


def _action(command):
    return {
        "AMAccepts": {"Container": "List", "Optional": True, "Types": ["com.apple.cocoa.string"]},
        "AMProvides": {"Container": "List", "Types": ["com.apple.cocoa.string"]},
        "AMActionVersion": "2.0.3",
        "AMApplication": ["Automator"],
        "AMParameterProperties": {key: {} for key in
                                  ["COMMAND_STRING", "CheckedForUserDefaultShell", "inputMethod", "shell", "source"]},
        "ActionBundlePath": "/System/Library/Automator/Run Shell Script.action",
        "ActionName": "Run Shell Script",
        "ActionParameters": {"COMMAND_STRING": command, "CheckedForUserDefaultShell": True,
                             "inputMethod": 0, "shell": "/bin/bash", "source": ""},
        "BundleIdentifier": "com.apple.RunShellScript",
        "CFBundleVersion": "2.0.3",
        "CanShowSelectedItemsWhenRun": False,
        "CanShowWhenRun": True,
        "Category": ["AMCategoryUtilities"],
        "Class Name": "RunShellScriptAction",
        "InputUUID": "C8858263-5046-4098-8CF3-1B35ED0AFD8D",
        "OutputUUID": "3D390149-4FB2-4776-86AC-47F0CB792F78",
        "UUID": "CC5869BF-7E01-4B42-8E5D-C13A8B2710BB",
        "UnlocalizedApplications": ["Automator"],
        "isViewVisible": 1,
        "nibPath": "/System/Library/Automator/Run Shell Script.action/Contents/Resources/Base.lproj/main.nib",
    }


def _metadata():
    return {
        "applicationBundleIDsByPath": {GHOSTTY_BUNDLE: GHOSTTY_IDENTIFIER},
        "applicationPaths": [GHOSTTY_BUNDLE],
        "inputTypeIdentifier": "com.apple.Automator.nothing",
        "outputTypeIdentifier": "com.apple.Automator.nothing",
        "presentationMode": 15,
        "processesInput": False,
        "serviceApplicationBundleIdentifier": GHOSTTY_IDENTIFIER,
        "serviceApplicationPath": GHOSTTY_BUNDLE,
        "serviceInputTypeIdentifier": "com.apple.Automator.nothing",
        "serviceOutputTypeIdentifier": "com.apple.Automator.nothing",
        "serviceProcessesInput": False,
        "systemImageName": "NSActionTemplate",
        "useAutomaticInputType": False,
        "workflowTypeIdentifier": "com.apple.Automator.servicesMenu",
    }


def _launcher(support):
    """Resolve the helper the same way the installing environment invoked it.

    The AppleScript calls this script rather than a bare interpreter so the
    project keeps working after the install method changes, and so uv/pipx
    virtual environments are used instead of the system Python.
    """
    entry = shutil.which("remote-image-paste") or ""
    if not entry:
        return None
    return ("#!/bin/sh\n"
            "# Generated by remote-image-paste install. Calls the installed console script.\n"
            "exec " + entry + ' "$@"\n')


def install(home, host, marker, directory=config_module.DEFAULT_DIRECTORY):
    home = Path(home)
    support, service, config_path = locations(home)
    if support.exists() or service.exists() or config_path.exists():
        raise ValueError(
            "Already installed, or a destination already exists. "
            "Uninstall first; existing files and configuration were left untouched.")

    config_module.validate(host, marker, directory)
    launcher_body = _launcher(support)
    if not launcher_body:
        raise ValueError(
            "The 'remote-image-paste' console script is not on PATH. "
            "Reinstall using the command from your package manager.")

    support.mkdir(parents=True)
    launcher = support / "remote-image-paste"
    launcher.write_text(launcher_body)
    launcher.chmod(0o755)

    applescript = support / "remote-image-paste.applescript"
    source = Path(__file__).resolve().parent / "resources" / "remote-image-paste.applescript"
    shutil.copyfile(source, applescript)
    applescript.chmod(0o644)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps(
        {"ssh_host": host, "terminal_title_contains": marker, "remote_directory": directory},
        indent=2) + "\n")

    contents = service / "Contents"
    contents.mkdir(parents=True)
    command = '/usr/bin/osascript "$HOME/Library/Application Support/remote-image-paste/remote-image-paste.applescript"'
    workflow = {"AMApplicationBuild": "534", "AMApplicationVersion": "2.10", "AMDocumentVersion": "2",
                "actions": [{"action": _action(command), "isViewVisible": 1}],
                "connectors": {}, "workflowMetaData": _metadata()}
    for name, data in (("Info.plist", _info_plist()), ("document.wflow", workflow)):
        with (contents / name).open("wb") as handle:
            plistlib.dump(data, handle)

    return {"config": config_path, "service": service, "support": support}


def uninstall(home):
    support, service, config_path = locations(home)
    removed = []
    for directory in (support, service):
        if directory.exists():
            shutil.rmtree(directory)
            removed.append(str(directory))
    # Configuration is deliberately retained so reinstalling keeps settings.
    return {"removed": removed, "config": config_path}


def check(host):
    """Confirm the configured host works without an interactive password prompt."""
    ensure = config_module.ensure_tool_path
    ensure()
    import subprocess
    from .upload import SSH_OPTIONS
    result = subprocess.run(["ssh", "-T", *SSH_OPTIONS, host, "printf ready"],
                            capture_output=True, text=True)
    return result.returncode == 0 and "ready" in result.stdout


def is_macos():
    return sys.platform == "darwin"


def ghostty_installed():
    return os.path.exists(GHOSTTY_BUNDLE)